### ISSUE TITLE
ottava lines

### ISSUE THREAD

**Issue by th-we** [rettinghaus/MEILER#25]
In MEI it seems common to encode written pitch with `@pname`/`@oct` so to say "ignoring" ottava brackets (at least that's what one find in the samples). Sounding pitch can optionally be encoded with `@pname.ges` and `@oct.ges`. Lilypond however wants the resulting transposed pitch encoded.

That's not really a problem - I'm currently thinking that I might wrap notes of an ottava bracket inside a `\transpose`. What I don't understand is what [`\unset Staff.middleCPosition`](https://github.com/rettinghaus/MEILER/blob/248087917919e76e7acbf03a3cee9d7d43ef0ba5/mei2ly.xsl#L1626) actually does. In any case it does weird things, e.g. for this example:

    <mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
      <meiHead>
        <fileDesc>
          <titleStmt>
            <title/>
          </titleStmt>
          <pubStmt/>
        </fileDesc>
      </meiHead>
      <music>
        <body>
          <mdiv>
            <score>
              <scoreDef meter.count="4" meter.unit="4">
                <staffGrp>
                  <staffDef n="1" clef.line="2" clef.shape="G" lines="5"/>
                  <staffDef n="2" clef.line="4" clef.shape="F" lines="5"/>
                </staffGrp>
              </scoreDef>
              <section>
                <measure n="1">
                  <staff n="1">
                    <layer n="1">
                      <note pname="c" oct="4" dur="2" oct.ges="3" xml:id="note1"/>
                      <note pname="c" oct="4" dur="2" oct.ges="3" xml:id="note2"/>
                    </layer>
                  </staff>
                  <staff n="2">
                    <layer n="1">
                      <note pname="c" oct="4" dur="2" oct.ges="3" xml:id="note3"/>
                      <note pname="c" oct="4" dur="2" oct.ges="3" xml:id="note4"/>
                    </layer>
                  </staff>
                  <octave dis="8" dis.place="below" startid="#note1" endid="#note1" staff="1"/>
                  <octave dis="8" dis.place="above" startid="#note2" endid="#note2" staff="1"/>
                  <octave dis="8" dis.place="below" startid="#note3" endid="#note3" staff="2"/>
                  <octave dis="8" dis.place="above" startid="#note4" endid="#note4" staff="2"/>
                </measure>
              </section>
            </score>
          </mdiv>
        </body>
      </music>
    </mei>

![bildschirmfoto vom 2017-03-12 19-13-06](https://cloud.githubusercontent.com/assets/1147152/23834514/f2b0a8e4-0757-11e7-9265-8afacc3493c3.png)

My plan would be:

* Get rid of `\unset Staff.middleCPosition` and use `\transpose` instead
* Introduce a switch that makes the `\transpose` optional as I'm not sure how thought through the convention found in the sample library is and one might want to encode "sounding" pitch rather than written pitch.

Any better ideas?

**Comment by rettinghaus** [comment]
Originally I didn't want to rely on `oct.ges`. So I tried to "fake" it (which obviously only works with standard G clefs). 
I'll give it some thoughts.

**Comment by th-we** [comment]
I'll try to take care of it by using the `\transpose` approach, at least to the extend that's manageable right now. It might be restricted to `<octave>` with `@startid/@endid` and a single voice. That would at least cover some use cases, but not others.

**Comment by rettinghaus** [comment]
this should be ok now
