### ISSUE TITLE
Symbols instead of strings for IDs

### ISSUE THREAD

**Issue by th-we** [rettinghaus/MEILER#26]
Urs recently suggested that symbols are more efficient than strings when used in Scheme's associated lists. @rettinghaus, would you support changing things from

    <xsl:value-of select="concat('\tweak id #&quot;', @xml:id, '&quot; ')" />

to

    <xsl:value-of select="concat('\tweak id #&apos;', @xml:id, ' ')" />

?

**Comment by rettinghaus** [comment]
Would do, but doesn't work (for me), so I won't. 
`\tweak id #'note-g2 g'`

I think we should wait for LilyPond 2.20 and switch over to `output-attributes`. 
http://lilypond.org/doc/v2.19/Documentation/changes/

Ok for you?

**Comment by th-we** [comment]
I'm currently using version 2.19.54, where it seems to work.

**Comment by rettinghaus** [comment]
I'm currently using version 2.19.56. So what do I do wrong?!? 
The internals say, it has to be a string.
http://lilypond.org/doc/v2.19/Documentation/internals/grob_002dinterface

**Comment by rettinghaus** [comment]
Interestingly 2.19.56 doesn't set ids at all. Seems to be a mac build problem.

**Comment by rettinghaus** [comment]
Obviously ids are deactivated in 2.19.56. I added a template here 8050955 to use `output-attributes` instead, which is not used by default for now. Please give it a try.
